# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_DT_CISCO_SG220_26)		+= cisco_sg220-26.dtb
dtb-$(CONFIG_DT_ZYXEL_GS1900_48HP)	+= zyxel_gs1900-48hp.dtb
dtb-$(CONFIG_DT_EDGECORE_ECS4100_12PH)	+= edgecore_ecs4100-12ph.dtb
